pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh 'pip install -r sample-app/requirements.txt'
            }
        }
        stage('Run App') {
            steps {
                echo 'Running the Python app...'
                sh 'python3 sample-app/app.py'
            }
        }
    }
}
